# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/0102432c-f516-40f2-93fa-65d802ff279a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7710359e-7e3e-44a6-9e3f-00e720fb5089".device = "/dev/disk/by-uuid/7710359e-7e3e-44a6-9e3f-00e720fb5089";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0740-E0BA";
      fsType = "vfat";
    };

  services = {
    fwupd.enable = true;
    xserver.videoDrivers = [ "amdgpu" ];
    openvpn.servers = {
      officeVPN = {
        config = '' config /root/nixos/openvpn/officeVPN.conf '';
        updateResolvConf = true;
      };
    };
    thinkfan = {
      enable = true;
    };
    fprintd = {
      enable = true;
      tod = {
        enable = true;
        driver = pkgs.libfprint-2-tod1-goodix;
      };
    };
  };

  hardware = {
    opengl.extraPackages = with pkgs; [
      rocmPackages.clr.icd
    ];
  };

  powerManagement.cpuFreqGovernor = "performance";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.hostName = "laptop-work";
}
