# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
   imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/69572e9f-16c2-4d3b-9b0e-9f365de658c3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-38b4cde7-3687-4fb2-9137-651f162ea1da".device = "/dev/disk/by-uuid/38b4cde7-3687-4fb2-9137-651f162ea1da";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A089-9DC8";
      fsType = "vfat";
    };


 services = {
    fwupd.enable = true;
    xserver.videoDrivers = [ "amdgpu" ];
    thinkfan = {
      enable = true;
      levels = [
        [
          0
          0
          60
        ]
        [
          1
          60
          65
        ]
        [
          2
          65
          70
        ]
        [
          3
          70
          73
        ]
        [
          4
          73
          75
        ]
        [
          5
          75
          80
        ]
        [
          "level auto"
          80
          32767
        ]
      ];
    };
  };  

  hardware = {
    opengl.extraPackages = with pkgs; [
      rocmPackages.clr.icd
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.hostName = "laptop-work";
}
